treemenu/menuapp/urls.py
from django.urls import path
from menuapp import views as menuapp

app_name = 'menuapp'

urlpatterns = [
    path('menu/', menuapp.menu, name='menu'),
]

treemenu/treemenu/urls.py
from django.contrib import admin
from django.urls import path, include
from menuapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include('menuapp.urls')),
]

treemenu/menuapp/models.py
from django.db import models
from django.urls import reverse


class Menu(models.Model):
    title = models.CharField(max_length=125, unique=True, verbose_name='Menu title')

    class Meta:
        verbose_name = 'Menu'
        verbose_name_plural = 'Menus'

    def __str__(self):
        return self.title


class Item(models.Model):
    title = models.CharField(max_length=125, verbose_name='Item title')
    menu = models.ForeignKey(Menu, blank=True, related_name='items', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='childrens', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Menu item'
        verbose_name_plural = 'Menu items'

    def get_absolute_url(self):
        return reverse('item_detail', args=[str(self.id)])

    def __str__(self):
        return self.title

treemenu/menuapp/views.py
from django.shortcuts import render
from menuapp.models import Menu


def index(request):
    menu_list = Menu.objects.all()
    context = {
        'menu_list': menu_list
    }
    return render(request, 'menuapp/index.html', context)


def menu(request):
    menu_list = Menu.objects.all()
    context = {
        'menu_list': menu_list
    }

    return render(request, "menuapp/menu.html", context)

treemenu/menuapp/templates/menuapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

treemenu/menuapp/templates/menuapp/index.html
{% extends 'menuapp/base.html' %}

{% block title %} Index Page {% endblock %}

{% block content %}
<h1>Список созданных меню:</h1>
{% for menu in menu_list %}
<li>{{ menu }}</li>
{% endfor %}
<h2>Создать меню и вложенные меню можно в <a href="http://127.0.0.1:8000/admin/">админке</a></h2>

<h3>Для рендера дерева укажите название меню в menu.html (draw_menu 'Название меню').
    <br>После чего откройте <a href="{% url 'menuapp:menu' %}">страницу меню</a></h3>


{% endblock %}

treemenu/menuapp/templates/menuapp/menu.html
{% extends 'menuapp/base.html' %}

{% block title %} Menu Page {% endblock %}

{% load draw_menu %}
{% block content %}

<!--Здесь рендерится меню. Вместо 'Menu1' и 'Menu2' укажите нужные имена-->
{% draw_menu 'Menu1' %}
{% draw_menu 'Menu2' %}

{% endblock %}

treemenu/menuapp/templates/menuapp/menu_render.html
<ul>
    {% for item in items %}
        <li>
            <a href="?{{ other_querystring }}&{{ menu }}={{ item.id }}">{{ item.title }}</a>
        </li>
        {% if item.child_items %}
            {% include 'menuapp/menu_render.html' with items=item.child_items %}
        {% endif %}

    {% endfor %}
</ul>